version: '3.8'
services:
  dbpostgres:
    image: postgres:latest
    environment:
        - POSTGRES_USER=${USER_DB}
        - POSTGRES_PASSWORD=${PASSWORD_DB}
        - POSTGRES_DB=db_snest
    restart: unless-stopped
    volumes:
      - ./docker/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  dbpostgres: